#!/bin/bash
function printToBuffers () {
  case $(( ( ( $1 + animW ) % 20 ) / 5 )) in
    3)
      buf[0]='  o'
      buf[1]='   \\'
      buf[2]='    \\   _'
      buf[3]='     \\ ( )'
      buf[4]='      \\_|_'
      buf[5]='       /  \\'
      buf[6]='     _/_   \\'
      buf[7]='    /  /    \\'
      buf[8]='    \\  \\     \\o'
      buf[9]='    "  "'
      buf[10]=''
      ;;
    2)
      buf[0]='       o'
      buf[1]='       |'
      buf[2]='       |'
      buf[3]='       |'
      buf[4]='      ( )'
      buf[5]='      _|_'
      buf[6]='       \\|'
      buf[7]='        |\\_'
      buf[8]='       /| /'
      buf[9]='       \\| \\'
      buf[10]='       "|o"'
      ;;
    1)
      buf[0]='            0'
      buf[1]='           /'
      buf[2]='      _   /'
      buf[3]='     ( ) /'
      buf[4]='     _|_/'
      buf[5]='    /  \\'
      buf[6]='   /   _\\_'
      buf[7]='  /   /  /'
      buf[8]=' /o   \\  \\'
      buf[9]='      "  "'
      buf[10]=''
      ;;
    *)
      buf[0]='o          0'
      buf[1]=' \\   _   /'
      buf[2]='  \\ ( ) /'
      buf[3]='   \\_|_/'
      buf[4]='     |'
      buf[5]='    _|_'
      buf[6]='   /  /'
      buf[7]='   \\  \\'
      buf[8]='   "  "'
      buf[9]=''
      buf[10]=''
      ;;
  esac
}

. anim

function advanceRenderingPosition () {
  let animX="${animX} - 5"
}

function waitBetweenFrames () {
  sleep 0.1
}

animate
