#!/bin/bash
function printToBuffers {
  case $(( ( $1 + animW ) % 24 )) in
    22|23)
      buf[ 0]=''
      buf[ 1]='               ,'
      buf[ 2]='                \\ _'
      buf[ 3]='                 \\_)'
      buf[ 4]='                  |'
      buf[ 5]='                  |'
      buf[ 6]='                  |'
      buf[ 7]='                 /'
      buf[ 8]='                /'
      buf[ 9]='                \\'
      buf[10]='                 \\'
      ;;
    20|21)
      buf[ 0]=''
      buf[ 1]=''
      buf[ 2]='                _'
      buf[ 3]='               (_)'
      buf[ 4]='                |\\'
      buf[ 5]='                | \\'
      buf[ 6]='                "  \\'
      buf[ 7]='                   /'
      buf[ 8]='                  /'
      buf[ 9]='                  \\'
      buf[10]='                   \\'
      ;;
    18|19)
      buf[ 0]=''
      buf[ 1]=''
      buf[ 2]='                   _'
      buf[ 3]='                  (_)'
      buf[ 4]='                   \\----='
      buf[ 5]='                    \\'
      buf[ 6]='                     \\'
      buf[ 7]='                     /'
      buf[ 8]='                    /'
      buf[ 9]='                    \\'
      buf[10]='                     \\'
      ;;
    16|17)
      buf[ 0]=''
      buf[ 1]=''
      buf[ 2]=''
      buf[ 3]='                       ,'
      buf[ 4]='                  _   /'
      buf[ 5]='                 (_) /'
      buf[ 6]='                  `------'
      buf[ 7]='                       /'
      buf[ 8]='                      /'
      buf[ 9]='                      \\'
      buf[10]='                       \\'
      ;;
    14|15)
      buf[ 0]=''
      buf[ 1]=''
      buf[ 2]='                   _'
      buf[ 3]='                  (_)'
      buf[ 4]='                    \\'
      buf[ 5]='                   / \\'
      buf[ 6]='                  /   \\'
      buf[ 7]="                 '     |"
      buf[ 8]='                       |'
      buf[ 9]='                        \\'
      buf[10]='                         \\'
      ;;
    12|13)
      buf[ 0]=''
      buf[ 1]='                  ,'
      buf[ 2]='                   \\_'
      buf[ 3]='                   (\\)'
      buf[ 4]='                     \\'
      buf[ 5]='                      \\'
      buf[ 6]='                       \\'
      buf[ 7]='                        \\'
      buf[ 8]='                         \\'
      buf[ 9]='                          \\'
      buf[10]='                           \\'
      ;;
    10|11)
      buf[ 0]=''
      buf[ 1]='                 ,'
      buf[ 2]='                  \\_'
      buf[ 3]='                  (\\)'
      buf[ 4]='                    \\'
      buf[ 5]='                     \\'
      buf[ 6]='                      \\'
      buf[ 7]='                       |'
      buf[ 8]='                       |____'
      buf[ 9]=''
      buf[10]=''
      ;;
    8|9)
      buf[ 0]='               _'
      buf[ 1]='              (_)'
      buf[ 2]='           =----\\'
      buf[ 3]='                 \\'
      buf[ 4]='                  \\'
      buf[ 5]='                  /'
      buf[ 6]='                 /'
      buf[ 7]='                 \\'
      buf[ 8]='                  \\'
      buf[ 9]=''
      buf[10]=''
      ;;
    6|7)
      buf[ 0]=''
      buf[ 1]=''
      buf[ 2]=''
      buf[ 3]='              _'
      buf[ 4]='             (_)'
      buf[ 5]='              /\\'
      buf[ 6]='             /  \\'
      buf[ 7]='            " ___\\'
      buf[ 8]='             /'
      buf[ 9]='            /'
      buf[10]='            '
      ;;
    4|5)
      buf[ 0]=''
      buf[ 1]=''
      buf[ 2]=''
      buf[ 3]=''
      buf[ 4]='            _'
      buf[ 5]='           (_)'
      buf[ 6]='            /\\'
      buf[ 7]='           /  \\'
      buf[ 8]='          "    \\'
      buf[ 9]='             /\\_\\'
      buf[10]='            /'
      ;;
    2|3)
      buf[ 0]=''
      buf[ 1]=''
      buf[ 2]=''
      buf[ 3]=''
      buf[ 4]='             _'
      buf[ 5]='            (_)'
      buf[ 6]='        =----\\'
      buf[ 7]='              \\'
      buf[ 8]='            ___\\'
      buf[ 9]='            \\'
      buf[10]='             \\'
      ;;
    *)
      buf[ 0]=''
      buf[ 1]=''
      buf[ 2]='             _'
      buf[ 3]='            (_)'
      buf[ 4]='        =----\\'
      buf[ 5]='              \\'
      buf[ 6]='               \\'
      buf[ 7]='               /'
      buf[ 8]='              /'
      buf[ 9]='              \\'
      buf[10]='               \\'
      ;;
  esac
}

. anim

function advanceRenderingPosition () {
  let animX="${animX} - 2"
}

function preAnim () {
  echo -e "\e[u\e[11B\c"
  for x in $(seq 1 ${animW})
  do
    echo -e "=\c"
  done
}

function postFrame () {
  echo -e "\e[u\e[11B\e[$(( $1 + 30 ))C\e[K"
}

animate
