#!/bin/bash
#      _         _         _         _
#     ( )       ( )       ( )       ( )
#     _|_       _|_       _|_       _|_
#   \/ | \     _||_\      \|/      _||_\
#     _|_ \     _|_       _/_       _|_
#     \ / _    /  |      /   \  _   | /
#      /\/     -¬ |     /     \/    | \_
#    _/          _|   _/           _|
function printToBuffers () {
  buf[0]='      _'
  buf[1]='     ( )'
  buf[2]='     _|_'
  case $(( ( $1 + animW )  % 8 )) in
    6|7)
      buf[3]='   \\/ | \\'
      buf[4]='     _|_ \\'
      buf[5]='     \\ / _'
      buf[6]='      /\\/'
      buf[7]='    _/'
      ;;
    4|5)
      buf[3]='     _||_\\'
      buf[4]='     _|_'
      buf[5]='    /  |'
      buf[6]='    -¬ |'
      buf[7]='      _|'
      ;;
    2|3)
      buf[3]='     \\|/'
      buf[4]='     _/_'
      buf[5]='    /   \\  _'
      buf[6]='   /     \\/'
      buf[7]=' _/'
      ;;
    1|*)
      buf[3]='    _||_\\'
      buf[4]='     _|_'
      buf[5]='     | /'
      buf[6]='     | \\_'
      buf[7]='    _|'
      ;;
  esac
}

. anim

function advanceRenderingPosition () {
  let animX="${animX} - 2"
}

animate
